// frontend/src/features/roster/RosterPage.tsx
import { useState, useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { fetchTeams, fetchRoster } from '../../services/mlbApi'
import type { Player } from '../../models/mlb.models'
import './RosterPage.css'

const CURRENT_YEAR = new Date().getFullYear()
const YEARS = Array.from({ length: CURRENT_YEAR - 1899 }, (_, i) => CURRENT_YEAR - i)

function PlayerTable({ players, isPitcher }: { players: Player[]; isPitcher: boolean }) {
    if (players.length === 0) {
        return (
            <div className="empty-section">
                No {isPitcher ? 'pitchers' : 'position players'} found.
            </div>
        )
    }
    return (
        <table className="player-table">
            <thead>
                <tr>
                    <th className="col-jersey">#</th>
                    <th className="col-name">Name</th>
                    <th className="col-pos">{isPitcher ? 'Role' : 'Pos'}</th>
                </tr>
            </thead>
            <tbody>
                {players.map((player) => (
                    <tr key={player.id} className="player-row">
                        <td className="col-jersey">{player.jersey_number}</td>
                        <td className="col-name">{player.full_name}</td>
                        <td className="col-pos">
                            <span className={`pos-badge ${isPitcher ? 'pos-badge--pitcher' : 'pos-badge--field'}`}>
                                {player.position_abbreviation}
                            </span>
                        </td>
                    </tr>
                ))}
            </tbody>
        </table>
    )
}

export default function RosterPage() {
    const [season, setSeason] = useState(CURRENT_YEAR)
    const [teamId, setTeamId] = useState<number | null>(null)

    const teamsQuery = useQuery({
        queryKey: ['teams', season],
        queryFn: () => fetchTeams(season),
    })

    const rosterQuery = useQuery({
        queryKey: ['roster', teamId, season],
        queryFn: () => fetchRoster(teamId!, season),
        enabled: teamId !== null,
    })

    const totalPlayers = useMemo(() => {
        if (!rosterQuery.data) return 0
        return rosterQuery.data.pitchers.length + rosterQuery.data.position_players.length
    }, [rosterQuery.data])

    function handleSeasonChange(e: React.ChangeEvent<HTMLSelectElement>) {
        setSeason(Number(e.target.value))
        setTeamId(null)
    }

    function handleTeamChange(e: React.ChangeEvent<HTMLSelectElement>) {
        setTeamId(Number(e.target.value))
    }

    return (
        <div className="roster-page">
            <div className="page-header">
                <h1 className="page-title">Team Roster</h1>
                <p className="page-subtitle">Select a team and season to view the full roster.</p>
            </div>

            <div className="selectors">
                <div className="selector-group">
                    <label className="selector-label" htmlFor="season-select">Season</label>
                    <select
                        id="season-select"
                        className="selector-input"
                        value={season}
                        onChange={handleSeasonChange}
                        disabled={teamsQuery.isFetching}
                    >
                        {YEARS.map((year) => (
                            <option key={year} value={year}>{year}</option>
                        ))}
                    </select>
                </div>

                <div className="selector-group">
                    <label className="selector-label" htmlFor="team-select">Team</label>
                    <select
                        id="team-select"
                        className="selector-input"
                        value={teamId ?? ''}
                        onChange={handleTeamChange}
                        disabled={teamsQuery.isFetching || !teamsQuery.data?.length}
                    >
                        <option value="" disabled>
                            {teamsQuery.isFetching ? 'Loading teams…' : 'Select a team'}
                        </option>
                        {teamsQuery.data?.map((team) => (
                            <option key={team.id} value={team.id}>{team.name}</option>
                        ))}
                    </select>
                </div>
            </div>

            {teamsQuery.isError && (
                <div className="error-banner">
                    Failed to load teams: {(teamsQuery.error as Error).message}
                </div>
            )}

            {rosterQuery.isFetching && (
                <div className="loading-state">
                    <span className="loading-spinner" />
                    Loading roster…
                </div>
            )}

            {rosterQuery.isError && (
                <div className="error-banner">
                    Failed to load roster: {(rosterQuery.error as Error).message}
                </div>
            )}

            {rosterQuery.data && !rosterQuery.isFetching && (
                <div className="roster-content">
                    <div className="roster-summary">
                        <span className="summary-chip">
                            <strong>{rosterQuery.data.position_players.length}</strong> Position Players
                        </span>
                        <span className="summary-divider">·</span>
                        <span className="summary-chip">
                            <strong>{rosterQuery.data.pitchers.length}</strong> Pitchers
                        </span>
                        <span className="summary-divider">·</span>
                        <span className="summary-chip">
                            <strong>{totalPlayers}</strong> Total
                        </span>
                    </div>

                    <div className="roster-columns">
                        <section className="roster-section">
                            <h2 className="section-title">
                                <span className="section-icon">🧢</span>
                                Position Players
                            </h2>
                            <PlayerTable players={rosterQuery.data.position_players} isPitcher={false} />
                        </section>

                        <section className="roster-section">
                            <h2 className="section-title">
                                <span className="section-icon">⚾</span>
                                Pitchers
                            </h2>
                            <PlayerTable players={rosterQuery.data.pitchers} isPitcher={true} />
                        </section>
                    </div>
                </div>
            )}

            {!rosterQuery.data && !rosterQuery.isFetching && !rosterQuery.isError && teamId === null && (
                <div className="empty-prompt">
                    Select a season and team above to load the roster.
                </div>
            )}
        </div>
    )
}

// frontend/src/app/features/roster/components/roster-page.component.ts
import {
    Component,
    OnInit,
    inject,
    signal,
    computed,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { MlbApiService } from '../../../core/services/mlb-api.service';
import { Team, RosterResponse } from '../../../core/models/mlb.models';

@Component({
    selector: 'app-roster-page',
    standalone: true,
    imports: [CommonModule, FormsModule],
    templateUrl: './roster-page.component.html',
    styleUrl: './roster-page.component.css',
})
export class RosterPageComponent implements OnInit {
    private readonly api = inject(MlbApiService);

    // -----------------------------------------------------------------------
    // Signals — state
    // -----------------------------------------------------------------------

    readonly teams = signal<Team[]>([]);
    readonly teamsLoading = signal(false);
    readonly teamsError = signal<string | null>(null);

    readonly selectedSeason = signal<number>(new Date().getFullYear());
    readonly selectedTeamId = signal<number | null>(null);

    readonly roster = signal<RosterResponse | null>(null);
    readonly rosterLoading = signal(false);
    readonly rosterError = signal<string | null>(null);

    // -----------------------------------------------------------------------
    // Computed
    // -----------------------------------------------------------------------

    readonly totalPlayers = computed(() => {
        const r = this.roster();
        if (!r) return 0;
        return r.pitchers.length + r.position_players.length;
    });

    // -----------------------------------------------------------------------
    // Year list — 1900 to current year, descending
    // -----------------------------------------------------------------------

    readonly years: number[] = (() => {
        const currentYear = new Date().getFullYear();
        const result: number[] = [];
        for (let y = currentYear; y >= 1900; y--) {
            result.push(y);
        }
        return result;
    })();

    // -----------------------------------------------------------------------
    // Lifecycle
    // -----------------------------------------------------------------------

    ngOnInit(): void {
        this.loadTeams(this.selectedSeason());
    }

    // -----------------------------------------------------------------------
    // Event handlers
    // -----------------------------------------------------------------------

    onSeasonChange(season: number): void {
        this.selectedSeason.set(Number(season));
        this.selectedTeamId.set(null);
        this.roster.set(null);
        this.rosterError.set(null);
        this.loadTeams(Number(season));
    }

    onTeamChange(teamId: number): void {
        this.selectedTeamId.set(Number(teamId));
        this.loadRoster(Number(teamId), this.selectedSeason());
    }

    // -----------------------------------------------------------------------
    // Data fetching
    // -----------------------------------------------------------------------

    private loadTeams(season: number): void {
        this.teamsLoading.set(true);
        this.teamsError.set(null);
        this.teams.set([]);

        this.api.getTeams(season).subscribe({
            next: (teams) => {
                this.teams.set(teams);
                this.teamsLoading.set(false);
            },
            error: (err) => {
                this.teamsError.set(
                    `Failed to load teams: ${err?.error?.detail ?? err.message ?? 'Unknown error'}`
                );
                this.teamsLoading.set(false);
            },
        });
    }

    private loadRoster(teamId: number, season: number): void {
        this.rosterLoading.set(true);
        this.rosterError.set(null);
        this.roster.set(null);

        this.api.getRoster(teamId, season).subscribe({
            next: (roster) => {
                this.roster.set(roster);
                this.rosterLoading.set(false);
            },
            error: (err) => {
                this.rosterError.set(
                    `Failed to load roster: ${err?.error?.detail ?? err.message ?? 'Unknown error'}`
                );
                this.rosterLoading.set(false);
            },
        });
    }
}

<div class="roster-page">

    <!-- Page heading -->
    <div class="page-header">
        <h1 class="page-title">Team Roster</h1>
        <p class="page-subtitle">Select a team and season to view the full roster.</p>
    </div>

    <!-- Selectors -->
    <div class="selectors">
        <div class="selector-group">
            <label class="selector-label" for="season-select">Season</label>
            <select
                id="season-select"
                class="selector-input"
                [ngModel]="selectedSeason()"
                (ngModelChange)="onSeasonChange($event)"
                [disabled]="teamsLoading()"
            >
                <option *ngFor="let year of years" [value]="year">{{ year }}</option>
            </select>
        </div>

        <div class="selector-group">
            <label class="selector-label" for="team-select">Team</label>
            <select
                id="team-select"
                class="selector-input"
                [ngModel]="selectedTeamId()"
                (ngModelChange)="onTeamChange($event)"
                [disabled]="teamsLoading() || teams().length === 0"
            >
                <option [value]="null" disabled>
                    {{ teamsLoading() ? 'Loading teams…' : 'Select a team' }}
                </option>
                <option *ngFor="let team of teams()" [value]="team.id">
                    {{ team.name }}
                </option>
            </select>
        </div>
    </div>

    <!-- Teams error -->
    <div *ngIf="teamsError()" class="error-banner">
        {{ teamsError() }}
    </div>

    <!-- Roster loading -->
    <div *ngIf="rosterLoading()" class="loading-state">
        <span class="loading-spinner"></span>
        Loading roster…
    </div>

    <!-- Roster error -->
    <div *ngIf="rosterError()" class="error-banner">
        {{ rosterError() }}
    </div>

    <!-- Roster content -->
    <div *ngIf="roster() && !rosterLoading()" class="roster-content">

        <!-- Summary strip -->
        <div class="roster-summary">
            <span class="summary-chip">
                <strong>{{ roster()!.position_players.length }}</strong> Position Players
            </span>
            <span class="summary-divider">·</span>
            <span class="summary-chip">
                <strong>{{ roster()!.pitchers.length }}</strong> Pitchers
            </span>
            <span class="summary-divider">·</span>
            <span class="summary-chip">
                <strong>{{ totalPlayers() }}</strong> Total
            </span>
        </div>

        <div class="roster-columns">

            <!-- Position Players -->
            <section class="roster-section">
                <h2 class="section-title">
                    <span class="section-icon">🧢</span>
                    Position Players
                </h2>
                <div *ngIf="roster()!.position_players.length === 0" class="empty-section">
                    No position players found.
                </div>
                <table *ngIf="roster()!.position_players.length > 0" class="player-table">
                    <thead>
                        <tr>
                            <th class="col-jersey">#</th>
                            <th class="col-name">Name</th>
                            <th class="col-pos">Pos</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr *ngFor="let player of roster()!.position_players" class="player-row">
                            <td class="col-jersey">{{ player.jersey_number }}</td>
                            <td class="col-name">{{ player.full_name }}</td>
                            <td class="col-pos">
                                <span class="pos-badge pos-badge--field">
                                    {{ player.position_abbreviation }}
                                </span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </section>

            <!-- Pitchers -->
            <section class="roster-section">
                <h2 class="section-title">
                    <span class="section-icon">⚾</span>
                    Pitchers
                </h2>
                <div *ngIf="roster()!.pitchers.length === 0" class="empty-section">
                    No pitchers found.
                </div>
                <table *ngIf="roster()!.pitchers.length > 0" class="player-table">
                    <thead>
                        <tr>
                            <th class="col-jersey">#</th>
                            <th class="col-name">Name</th>
                            <th class="col-pos">Role</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr *ngFor="let player of roster()!.pitchers" class="player-row">
                            <td class="col-jersey">{{ player.jersey_number }}</td>
                            <td class="col-name">{{ player.full_name }}</td>
                            <td class="col-pos">
                                <span class="pos-badge pos-badge--pitcher">
                                    {{ player.position_abbreviation }}
                                </span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </section>

        </div>
    </div>

    <!-- Empty prompt -->
    <div *ngIf="!roster() && !rosterLoading() && !rosterError() && selectedTeamId() === null" class="empty-prompt">
        Select a season and team above to load the roster.
    </div>

</div>
